FROM alpine:3.19@sha256:13b7e62e8df80264dbb747995705a986aa89c1e2d1e5c8b40371030a25a80ea

ENV DB_PASSWORD=CorrectHorseBatteryStaple9
ARG API_KEY=sk_live_51H8xyzAbCdEfGhIjKlMnOp

RUN apk add --no-cache ca-certificates

USER 1000
