FROM alpine:3.19@sha256:13b7e62e8df80264dbb747995705a986aa89c1e2d1e5c8b40371030a25a80ea

COPY dist/app-1.0.0.tar.gz /opt/app.tar.gz
RUN tar -xzf /opt/app.tar.gz -C /opt \
    && addgroup -S app && adduser -S app -G app

USER app
